version: 0.2

#env:
  #variables:
     # key: "value"
     # key: "value"
  #parameter-store:
     # key: "value"
     # key: "value"

phases:
  install:
    runtime-versions:
      python: 3.7

    commands:
      - pip install --upgrade pip
      - apt-get update -y
      - pip install -r requirements.txt

  #pre_build:
    #commands:
      # - command
  build:
    commands:
      - ls
      - cd sam-app
      - ls
      #- export PYTHONPATH=.
      - python -m pytest ./tests/ -v
      
  post_build:
    commands:
      - sam package \ 
        --output-template-file packaged.yaml \
        --s3-bucket my-denis-bucket

      - echo Build completed on `date`

#artifacts:
  #files:
    # - location
    # - location
  #name: $(date +%Y-%m-%d)
  #discard-paths: yes
  #base-directory: location
cache:
  paths:
    - '/root/.cache/pip'